### ISSUE TITLE
Allow use of stateful Allocator passed into construtors

### ISSUE THREAD

**Issue by jmalkin** [apache/datasketches-cpp#160]
Criteo's Vertica integration has noted that our current use of custom allocators is less flexible than ideal:  https://github.com/criteo/vertica-datasketch

**Comment by AlexanderSaydakov** [comment]
Passing allocators to constructors is implemented for Tuple sketch and experimental Theta sketch (located in the "tuple" directory for now) that eventually should replace the current Theta sketch. Feedback is appreciated.

**Comment by jmalkin** [comment]
This should now be resolved everywhere.
