### ISSUE TITLE
Is there a HllMap C++ implementation?

### ISSUE THREAD

**Issue by bryanherger** [apache/datasketches-cpp#184]
Is the HllMap available here?  I see it on the website documentation and in datasketches-java, but not sure what is equivalent here.

**Comment by AlexanderSaydakov** [comment]
HllMap in Java exists to address the problem of object overhead. Imagine a HashMap from a standard Java library with tens or hundreds of thousands of pairs, say, Integer to HllSketch. Just the object overhead will take a lot of memory. There is no such problem in C++. Try something like std::unordered_map<int, hll_sketch>. I believe it should work fine. Please let us know if you encounter any problem.

**Comment by bryanherger** [comment]
Thank you, I will try that.
