### ISSUE TITLE
`theta_update_sketch_base` is not exception safe.

### ISSUE THREAD

**Issue by alexey-milovidov** [apache/datasketches-cpp#210]
theta_update_sketch_base_impl.hpp:

```
template<typename EN, typename EK, typename A>
void theta_update_sketch_base<EN, EK, A>::resize() {
  ...
  lg_cur_size_ += factor;    <-- the size is increased here
  ...
  entries_ = allocator_.allocate(new_size);    <-- an exception can be thrown here
  ...
}

While unwinding the stack, destructor is called:

template<typename EN, typename EK, typename A>
theta_update_sketch_base<EN, EK, A>::~theta_update_sketch_base()
{
    ...
    const size_t size = 1 << lg_cur_size_;    <-- wrong size is calculated
    for (size_t i = 0; i < size; ++i) {
      if (EK()(entries_[i]) != 0) entries_[i].~EN();    <-- memory corruption
    }
    allocator_.deallocate(entries_, size);      <-- method is called with wrong argument
  }
}
```

The issue has been found while we tried to integrate the library into [ClickHouse](https://clickhouse.tech/):
https://github.com/ClickHouse/ClickHouse/pull/23334

ClickHouse has powerful fuzzing infrastructure (you can read about it [here](https://clickhouse.tech/blog/en/2021/fuzzing-clickhouse/)).

**Comment by alexey-milovidov** [comment]
Memory leak is also suspected here:

```
  EN* old_entries = entries_;        <-- old_entries are owned by no one
  entries_ = allocator_.allocate(new_size);
  for (size_t i = 0; i < new_size; ++i) EK()(entries_[i]) = 0;
  num_entries_ = 0;
  for (size_t i = 0; i < old_size; ++i) {
    const uint64_t key = EK()(old_entries[i]);
    if (key != 0) {
      insert(find(key).first, std::move(old_entries[i])); // consider a special insert with no comparison
      old_entries[i].~EN();
    }
  }
  allocator_.deallocate(old_entries, old_size);
```

**Comment by AlexanderSaydakov** [comment]
I think I have a fix for the first issue. Regarding the second, you are right, potentially, if ~EN() can throw. Not in theta sketch, but in tuple sketch, where EN includes user type T. Perhaps we should always wrap pointers in uniq_ptr, but that adds so much ugly code because of custom allocator and deleter.
Besides, if ~EN() can throw, we can leak in the destructor of this class as well. Should we have try{} around each destructor call?

**Comment by alexey-milovidov** [comment]
Throwing destructors should not be considered, it's ok to assume that destructors don't throw or std::terminate is called.

**Comment by alexey-milovidov** [comment]
Maybe `EK()` can throw? But I did not check what is EK yet...

**Comment by AlexanderSaydakov** [comment]
no EK() is a trivial operation: for theta sketch it is pass-through, for tuple sketch it returns EN.first (it is an std::pair<uint64_t, T>)
