### ISSUE TITLE
The library is not UBSan friendly.

### ISSUE THREAD

**Issue by alexey-milovidov** [apache/datasketches-cpp#211]
Unaligned memory access: https://github.com/apache/datasketches-cpp/commit/6ea39e30f48ef9736a25b5323dd4d33726ee8e02

This issue has been found while we tried to integrate the library to [ClickHouse](https://github.com/ClickHouse/ClickHouse).
ClickHouse is tested with ASan, MSan, TSan and UBSan with several kinds of continuous fuzzing.

**Comment by jmalkin** [comment]
Do you have a minimum test case that fails? I was unable to reproduce this when running locally.

**Comment by AlexanderSaydakov** [comment]
@jmalkin It may or may not fail depending on platform and compiler. UBSan catches undefined behavior that potentially might fail somewhere.

**Comment by AlexanderSaydakov** [comment]
@alexey-milovidov Would you like to submit a pull request or would you like us to apply your suggested patch? Thank you.

**Comment by jmalkin** [comment]
@AlexanderSaydakov yes, I added flags to compile and link with UBSan and ASan using `-fcoverage` options and found nothing. I may well be doing something incorrectly, of course.

**Comment by alexey-milovidov** [comment]
It's ok if you commit this patch under your name. My collegue will share an example, but only tomorrow.
