### ISSUE TITLE
Getting Attribute Error: type object 'datasketches.theta_sketch' has no attribute 'deserialize'

### ISSUE THREAD

**Issue by Shubham-Jha-GT** [apache/datasketches-cpp#224]
We are using datasketches library to perform union/intersection operations and compute datasketches. Everything was working fine on an older laptop with `datasketches===2.2.0-incubating-SNAPSHOT`.

We tried installing the latest version of the datasketches module (`datasketches==3.1.0.dev0`) and now its failing to run our python script with `Attribute Error: type object 'datasketches.theta_sketch' has no attribute 'deserialize'`

I've attached the terminal commands and output in the following text file
[Datasketches_installtion_terminal.txt](https://github.com/apache/datasketches-cpp/files/6731222/Datasketches_installtion_terminal.txt)

This is the function in which we're trying to call the deserialize object - 

`    def get_sketches(bucket, values, logger):
        value_string = str([str(i) for i in values])[1:-1]

        SELECT_QUERY = "SELECT value, sketch FROM {table} WHERE bucket='{bucket}' AND value in ({values}) AND timestamp::DATE = '{date}'"
        query = SELECT_QUERY.format(
            table=SINGLE_DAY_SKETCH_TABLE,
            bucket=bucket,
            values=value_string,
            date=DATE
        )
        logger.info("SQL: " + query)
        result = run_select_query(query)
        logger.info("Data fetched from DB.")

        sketch_list = []
        for row in result:
            if bucket in ('brand', 'sic', 'dma'):
                value = int(row[0])
            else:
                value = row[0]
            sketch_string = row[1]
            sketch_obj = datasketches.theta_sketch.deserialize(bytes(sketch_string))
            sketch_list.append((value, sketch_obj))

        return sketch_list`
        
This script is working perfectly fine in the older laptop with 2.2.0 version.

would really appreciate any help on this.

Thanks

**Comment by AlexanderSaydakov** [comment]
Since 3.0.0 release only compact_theta_sketch can be serialized and deserialized

**Comment by Shubham-Jha-GT** [comment]
okay thanks. can you please guide how to use that ?

**Comment by Shubham-Jha-GT** [comment]
for the time being, we have downgraded the version to 2.1.x and its working for now. Will try to modify script as per latest versions. Thanks :)
