### ISSUE TITLE
sketch_union classes need reset() method

### ISSUE THREAD

**Issue by will-lauer** [apache/datasketches-cpp#243]
When unioning sketches together, it is often useful to be able to reset the union rather than freeing and reallocating a new object. `reset()` methods should be added to theta_union, tuple_union, and any and all other union classes to allow the computation to be reset back to its initial state.

**Comment by AlexanderSaydakov** [comment]
This feature was implemented a while ago for Theta and Tuple sketches, and is a part of 3.3.0 release. Reset may or may not be cheaper than starting a new object depending on implementation details.
