### ISSUE TITLE
Is it possible to estimate the fraction of a single frequent value?

### ISSUE THREAD

**Issue by FluorineDog** [apache/datasketches-cpp#251]
After building the kll_sketch with a stream of values, we call `get_quantiles(101)` to get 100 buckets with lower bounds and upper bounds, and estmate their fraction calling the `get_ratio` for each bound to get a closest estimate. 

We found that if there is a frequent value X having 30% fraction, there will be around 30 buckets holding lower_bound=upper_bound=X, which is understandable and we will merge these buckets into one. 

However, I wonder if it's possible to get the estimated count directly from kll_sketch? Doing that will make our life much easier.

**Comment by AlexanderSaydakov** [comment]
There is no easy way to get a probability distribution mass for a single item currently. And you need to know the item first. If you knew the next item in the rank order, you could do rank(next) - rank(item).

This seems like an attempt to solve a problem with a wrong tool. There is a Frequent Items sketch in the library for that. If you are looking for very heavy items, your sketch can be rather small. For instance, size of 32 is enough to capture items heavier than about 11% of the input.

https://datasketches.apache.org/docs/Frequency/FrequentItemsErrorTable.html
