### ISSUE TITLE
datasketches does not work with python 3.9

### ISSUE THREAD

**Issue by MaheshGPai** [apache/datasketches-cpp#262]
Datasketches module 3.2.0.1 seems to have been compiled with python 3.10 and does not work with python 3.9

> root@907f428e7dc2:/temp# pip install datasketches --target .
Collecting datasketches
  Downloading datasketches-3.2.0.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (474 kB)
     |████████████████████████████████| 474 kB 658 kB/s 
Collecting numpy
  Downloading numpy-1.22.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.8 MB)
     |████████████████████████████████| 16.8 MB 7.3 MB/s 
Installing collected packages: numpy, datasketches
Successfully installed datasketches-3.2.0.1 numpy-1.22.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
WARNING: You are using pip version 21.2.4; however, version 22.0.3 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

> root@907f428e7dc2:/temp# ls -lrt
total 1056
drwxr-xr-x  2 root root    4096 Feb 12 06:16 numpy.libs
drwxr-xr-x 19 root root    4096 Feb 12 06:16 numpy
drwxr-xr-x  2 root root    4096 Feb 12 06:16 bin
drwxr-xr-x  2 root root    4096 Feb 12 06:16 numpy-1.22.2.dist-info
-rwxr-xr-x  1 root root 1049008 Feb 12 06:16 datasketches.cpython-310-x86_64-linux-gnu.so
drwxr-xr-x  3 root root    4096 Feb 12 06:16 tests
drwxr-xr-x  3 root root    4096 Feb 12 06:16 src
drwxr-xr-x  2 root root    4096 Feb 12 06:16 datasketches-3.2.0.1.dist-info

> root@907f428e7dc2:/temp# python
Python 3.9.10 (main, Jan 26 2022, 20:56:53) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datasketches
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'datasketches'

As per the below link 3.9 is supported
https://www.piwheels.org/project/datasketches/

But the compiled library is that of 3.10  : datasketches.cpython-**310**-x86_64-linux-gnu.so

**Comment by MaheshGPai** [comment]
> root@907f428e7dc2:/temp# ln -s datasketches.cpython-310-x86_64-linux-gnu.so datasketches.so

>root@907f428e7dc2:/temp# python
Python 3.9.10 (main, Jan 26 2022, 20:56:53) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datasketches
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Python version mismatch: module was compiled for Python 3.10, but the interpreter version is incompatible: 3.9.10 (main, Jan 26 2022, 20:56:53) 
[GCC 10.2.1 20210110].

**Comment by MaheshGPai** [comment]
Thanks @jmalkin. It works on my mac too. I hit this issue when I deployed my application using AWS lambda. It currently support only python 3.9. And this issue is seen even when I use python's 3.9 linux container. Have not tried this on windows.

**Comment by jmalkin** [comment]
@MaheshGPai Which specific python 3.9 container were you using for this? They seem to have lots of variants.

I haven't done much with python containers, so if you can share a minimal Dockerfile that'd be appreciated. I was clearly running into path issues when experimenting yesterday.

**Comment by MaheshGPai** [comment]
https://hub.docker.com/layers/python/library/python/3.9.10/images/sha256-6f468ed026185ad7f1a13d1dde8f307449fce3777695bfacf91da8f7987b5fd5?context=explore

**Comment by MaheshGPai** [comment]
I got this working by building datasketches using python 3.9.10.

**Comment by jsurloppe** [comment]
Hello,

I run against this issue on another version, after looking into, its looks like the current package on pypi (3.2.0.1) is incorrect, the .so file in all wheel is build for python 3.10 (`datasketches.cpython-310-x86_64-linux-gnu.so`), so it doesn't load on other versions than 3.10.

**Comment by jmalkin** [comment]
Sorry, I haven't had a chance to get to this. Still quite backlogged.

The underlying issue is that cibuildwheel is only generating with 3.10, even when the naming suggests it should be otherwise. But I have no clue why this is happening. Presumably there's something incorrectly configured in the github action that generates the set of wheels.

**Comment by jmalkin** [comment]
Trying to cycle back to this finally. My best guess right now is that cmake is automatically finding a different version of python from what cibuildwheel expects. But that's pure speculation -- the only thing I can really confirm is that a newer version of cibuildwheel didn't fix it.

**Comment by jmalkin** [comment]
Ok, way too slow addressing this, but I think the artifact.zip at https://github.com/apache/datasketches-cpp/actions/runs/2261547153 (the link is at the bottom) should work. If anyone is still following this and able to try it, please let me know.

**Comment by jmalkin** [comment]
This should be resolved if you build yourself. For a pre-built artifact, we need to wait for the next release.

**Comment by jmalkin** [comment]
3.4.0 has been released on pypi which should finally close this out.
