### ISSUE TITLE
static analyzer detects a possible bug

### ISSUE THREAD

**Issue by FluorineDog** [apache/datasketches-cpp#287]
Recently, we run static analyzer on our project, and it reports the following problem:

https://github.com/apache/datasketches-cpp/blob/ce4d82c6807bbf0ed9b993d810a22320d53d0747/cpc/include/cpc_compressor_impl.hpp#L299-L300

L299 get `pseudo_phase`, which could be `16 + x`. But the `column_permutations_for_encoding` is a fixed 2-D array with dimension `[16][59]`, so it's a possible overflow. 

If this is a false positive, maybe we should add a check like the following (found in the coresponding uncompress method) to make the static analyzer happy?

 https://github.com/apache/datasketches-cpp/blob/ce4d82c6807bbf0ed9b993d810a22320d53d0747/cpc/include/cpc_compressor_impl.hpp#L336

**Comment by AlexanderSaydakov** [comment]
I looked at the code, and I believe that in this mode the pseudo phase must be within the range from 0 to 15. So I would agree with you that we could check that as you suggest.

**Comment by FluorineDog** [comment]
I mean my company's database project including this as a third-party lib. We are introduing static analyzer to improve quailty of code.
