### ISSUE TITLE
std::iterator is deprecated; replace it

### ISSUE THREAD

**Issue by jbapple** [apache/datasketches-cpp#328]
`std::iterator` is deprecated; see https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2016/p0174r2.html#2.1. It is used ten times in datasketches-cpp:

```
$ git grep -c std::iterator
fi/include/reverse_purge_hash_map.hpp:1
hll/include/HllArray.hpp:1
hll/include/coupon_iterator.hpp:1
kll/include/kll_sketch.hpp:1
quantiles/include/quantiles_sketch.hpp:1
req/include/req_sketch.hpp:1
sampling/include/var_opt_sketch.hpp:2
theta/include/theta_update_sketch_base.hpp:2
```

Replace these inheritances with explicit using/typedef declarations in each class.

**Comment by jmalkin** [comment]
Not sure exactly when we'll get to this, but this is a good point. We only target C++11, which is prior to deprecation, but these changes won't break compatibility with that version. Definitely worth doing as there's an upside for future compatibility with no obvious drawbacks.

**Comment by jmalkin** [comment]
I think some of our existing tasks are wrapping up, so with luck we'll be able to take this up shortly.

**Comment by jmalkin** [comment]
I don't seem to get g++ or clang++ to complain about this even if I use c++17.  Not trying to suggest that it's not an issue, just that I'd expected to be complained at. Weird.

**Comment by jbapple** [comment]
You might try with Clang 16 using C++20 and libc++.

**Comment by jmalkin** [comment]
@AlexanderSaydakov There's something going with theta sketches that makes things fail if I just remove std::iterator and define the 5 necessary types.

**Comment by jmalkin** [comment]
#342 will address this. It might need some tweaks first.

**Comment by jmalkin** [comment]
And it has been merged. Might not be perfect -- we welcome any feedback -- but it's certainly better than before.

**Comment by jmalkin** [comment]
As a final follow-up, this has now been Officially Released.
