### ISSUE TITLE
random_utils is not thread-safe

### ISSUE THREAD

**Issue by FluorineDog** [apache/datasketches-cpp#349]
In our project, we use multiple kll_sketch in parallel. But it depends on random_bits: 
https://github.com/apache/datasketches-cpp/blob/fa0dce5180f845020ec9c6e034ee134f1f91d580/common/include/common_defs.hpp#L40-L48
which is not thread-safe, making Thread Sanitizer(TSAN) complain about data race. 

I make a [PR](https://github.com/apache/datasketches-cpp/pull/347) to solve this. it needs your approve to start ci. plz check it.

**Comment by AlexanderSaydakov** [comment]
Could you answer my questions in the pull request please?
Thank you.

**Comment by AlexanderSaydakov** [comment]
should be fixed by #347

**Comment by jmalkin** [comment]
This was included in v4.1.0, which has now officially been released.
