### ISSUE TITLE
Python scripts.

### ISSUE THREAD

**Issue by cgoat** [apache/datasketches-cpp#421]
Is there a Python adapter for the Data sketches. This page (https://datasketches.apache.org/docs/Community/Transitioning.html)  has a link that does not seem to be working.

**Comment by jmalkin** [comment]
We now have a separate repo, [https://github.com/apache/datasketches-python/](https://github.com/apache/datasketches-python), and were preparing for a release but we found some issues with it. Until that's fixed, you can either look at this repo's 4.1.0 release or install from pypi (which is also the 4.1.0 release).

**Comment by cgoat** [comment]
Thank you. Appreciate the prompt response.
